spring:

  datasource:
    url: jdbc:mysql://localhost:3306/DBPizzariaZeff
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false